
name = "Classification tutorial (EMPIAR-10304)"
description = """\
    This tutorial shows the end-to-end process to convert tilt-series from EMPIAR-10304 (ribosome) into multiple structures in different conformations.\
    """

# comments here are useful to share info with other workflow authors looking at this file
[blocks.rawdata]
blockId = "tomo-rawdata"
name = "Raw Data"

[blocks.rawdata.args]
data_path = { ask = true }
scope_pixel = 2.1
scope_voltage = 300
scope_tilt_axis = 90.0

[blocks.preprocessing]
blockId = "tomo-pure-preprocessing"
name = "Pre-processing"
parent = "rawdata"

[blocks.preprocessing.args]
movie_no_frames = true
ctf_max_res = 5.0
tomo_ali_format = false
tomo_rec_binning = 12
tomo_rec_thickness = 3072
tomo_rec_erase_fiducials = true
slurm_tasks = { ask = true }            # e.g.: 42 for pre-processing, 124 for refinement
slurm_merge_tasks = { ask = true }      # e.g.: 13 for refinement, 100 for classification
slurm_memory_per_task = { ask = true }

[blocks.particlepicking]
blockId = "tomo-picking"
name = "Particle picking"
parent = "preprocessing"

[blocks.particlepicking.args]
tomo_pick_method = "auto"
tomo_pick_rad = 80
tomo_pick_stdtimes_cont_3d = 2.0
tomo_pick_min_size_3d = 60
tomo_pick_dilation_3d = 100
tomo_pick_radiustimes_3d = 2.0
tomo_pick_inhibit_3d = true
tomo_pick_stdtimes_filt_3d = 2.0
tomo_pick_detection_width_3d = 40.0

[blocks.reference_refinement]
blockId = "tomo-reference-refinement"
name = "Reference-based refinement"
parent = "particlepicking"

[blocks.reference_refinement.args]
particle_mw = 2000
particle_rad = 150
extract_box = 64
extract_bin = 4
extract_gold = false
extract_ctf_handedness = true
# refine_skip = true
metric_rhref = "22.0"
metric_fboost = true
metric_UseImagesForRefinementMin = 15
metric_UseImagesForRefinementMax = 25
reconstruct_mintilt = -50
reconstruct_maxtilt = 50
csp_tomo_reference_ToleranceParticlesPhi = 180.0
csp_tomo_reference_ToleranceParticlesTheta = 180.0
csp_tomo_reference_ToleranceParticlesPsi = 180.0
csp_tomo_reference_AngleStep = 6
csp_tomo_reference_ToleranceParticlesShifts = 50.0
csp_tomo_reference_ShiftStep = 4.32

[blocks.particle_filtering]
blockId = "tomo-fine-refinement"
name = "Particle filtering"
parent = "reference_refinement"

[blocks.particle_filtering.args]
clean_threshold = 15.0
clean_dist = 20.0
clean_mintilt = -7.0
clean_maxtilt = 7.0
clean_min_num_projections = 1
clean_check_reconstruction = true
clean_parfile = 'auto'
clean_discard = true

[blocks.constrained_refinement]
blockId = "tomo-new-coarse-refinement"
name = "Fully constrained refinement"
parent = "particle_filtering"

[blocks.constrained_refinement.args]
particle_mw = 2000
particle_rad = 150
extract_box = 256
extract_bin = 1
extract_ctf_handedness = true
# refine_skip = true
metric_rhref = "18:14"
refine_fboost = true
metric_UseImagesForRefinementMin = 15
metric_UseImagesForRefinementMax = 25
csp_tomo_coarse_parfile = "auto"
csp_tomo_coarse_maxiter = 3
csp_tomo_coarse_refine_particles = true
csp_tomo_coarse_refine_micrographs = true
csp_tomo_coarse_OptimizerStepLength = 100.0
csp_tomo_coarse_ToleranceParticlesPsi = 30.0
csp_tomo_coarse_ToleranceParticlesPhi = 30.0
csp_tomo_coarse_ToleranceParticlesTheta = 30.0
csp_tomo_coarse_ToleranceParticlesShifts = 30.0
reconstruct_dose_weighting_enable = true
reconstruct_dose_weighting_fraction = 4
reconstruct_dose_weighting_global = true

[blocks.mask_generation]
blockId = "sp-masking"
name = "Create shape mask"
parent = "constrained_refinement"

[blocks.mask_generation.args]
mask_model = "auto"
mask_threshold = 0.4
mask_edge_width = 8

[blocks.region_refinement]
blockId = "tomo-new-coarse-refinement"
name = "Region-based refinement"
parent = "constrained_refinement"

[blocks.region_refinement.args]
particle_mw = 2000
particle_rad = 150
extract_box = 256
extract_bin = 1
extract_ctf_handedness = true
# refine_skip = true
metric_rhref = "12:10:8:6:5"
metric_fboost = true
metric_UseImagesForRefinementMin = 18
metric_UseImagesForRefinementMax = 22
metric_masking_method = "file"
metric_maskth = "auto"
csp_tomo_coarse_parfile = "auto"
csp_tomo_coarse_maxiter = 6
csp_tomo_coarse_refine_particles = true
csp_tomo_coarse_refine_micrographs = true
csp_tomo_coarse_OptimizerStepLength = 100.0
csp_tomo_coarse_NumberOfRandomIterations = 0
csp_tomo_coarse_ToleranceMicrographTiltAngles = 5.0
csp_tomo_coarse_ToleranceMicrographTiltAxisAngles = 5.0
csp_tomo_coarse_ToleranceParticlesPsi = 5.0
csp_tomo_coarse_ToleranceParticlesPhi = 5.0
csp_tomo_coarse_ToleranceParticlesTheta = 5.0
csp_tomo_coarse_ToleranceParticlesShifts = 20.0
csp_tomo_coarse_Grid = "8,8,2"
reconstruct_dose_weighting_enable = true
reconstruct_dose_weighting_fraction = 4
reconstruct_dose_weighting_global = true

[blocks.ctf_refinement]
blockId = "tomo-new-coarse-refinement"
name = "Particle-based CTF refinement"
parent = "region_refinement"

[blocks.ctf_refinement.args]
particle_mw = 2000
particle_rad = 150
extract_box = 256
extract_bin = 1
extract_ctf_handedness = true
# refine_skip = true
metric_rhref = "4.5"
metric_fboost = true
metric_UseImagesForRefinementMin = 15
metric_UseImagesForRefinementMax = 25
metric_masking_method = "file"
metric_maskth = "auto"
csp_tomo_coarse_parfile = "auto"
csp_tomo_coarse_maxiter = 2
csp_tomo_coarse_refine_particles = false
csp_tomo_coarse_refine_micrographs = false
csp_tomo_coarse_refine_ctf = true
csp_tomo_coarse_OptimizerStepLength = 100.0
csp_tomo_coarse_NumberOfRandomIterations = 0
csp_tomo_coarse_ToleranceMicrographDefocus1 = 2000
csp_tomo_coarse_ToleranceMicrographDefocus2 = 2000
csp_tomo_coarse_Grid = "8,8,2"
reconstruct_dose_weighting_enable = true
reconstruct_dose_weighting_fraction = 4
reconstruct_dose_weighting_global = true

[blocks.region_refinement_2]
blockId = "tomo-new-coarse-refinement"
name = "Region-based refinement 2"
parent = "ctf_refinement"

[blocks.region_refinement_2.args]
particle_mw = 2000
particle_rad = 150
extract_box = 256
extract_bin = 1
extract_ctf_handedness = true
# refine_skip = true
metric_rhref = "6:5:4.5"
metric_fboost = true
metric_UseImagesForRefinementMin = 18
metric_UseImagesForRefinementMax = 22
metric_masking_method = "file"
metric_maskth = "auto"
csp_tomo_coarse_parfile = "auto"
csp_tomo_coarse_maxiter = 4
csp_tomo_coarse_refine_particles = true
csp_tomo_coarse_refine_micrographs = true
csp_tomo_coarse_refine_ctf = false
csp_tomo_coarse_OptimizerStepLength = 20.0
csp_tomo_coarse_NumberOfRandomIterations = 0
csp_tomo_coarse_ToleranceMicrographShifts = 20.0
csp_tomo_coarse_ToleranceMicrographTiltAngles = 5.0
csp_tomo_coarse_ToleranceMicrographTiltAxisAngles = 5.0
csp_tomo_coarse_ToleranceParticlesPsi = 5.0
csp_tomo_coarse_ToleranceParticlesPhi = 5.0
csp_tomo_coarse_ToleranceParticlesTheta = 5.0
csp_tomo_coarse_ToleranceParticlesShifts = 20.0
csp_tomo_coarse_Grid = "16,16,4"
reconstruct_dose_weighting_enable = true
reconstruct_dose_weighting_fraction = 2
reconstruct_dose_weighting_global = true

[blocks.constrained_classification]
blockId = "tomo-new-coarse-classification"
name = "Constrained classification"
parent = "region_refinement_2"

[blocks.constrained_classification.args]
particle_mw = 2000
particle_rad = 150
extract_box = 256
extract_bin = 1
extract_ctf_handedness = true
# refine_skip = false
metric_rhref = "8"
metric_fboost = true
metric_masking_method = "file"
metric_maskth = "auto"
# refine_refine_angle_phi = false
# refine_refine_angle_psi = false
# refine_refine_angle_theta = false
csp_tomo_classification_maxiter = 20
csp_tomo_classification_parfile = "auto"
csp_tomo_classification_refine_particles = false
# csp_tomo_classification_Grid = "1,1,1"
csp_tomo_classification_num = 8
csp_tomo_classification_rhcls = 8.0
reconstruct_dose_weighting_enable = true
reconstruct_dose_weighting_fraction = 2
reconstruct_dose_weighting_weights = "auto"
