
name = "Classification tutorial (EMPIAR-10304)"
description = """\
    This tutorial shows the end-to-end process to convert tilt-series from EMPIAR-10304 (ribosome) into multiple structures in different conformations.\
    """

# comments here are useful to share info with other workflow authors looking at this file
[blocks.rawdata]
blockId = "tomo-rawdata"
name = "Raw Data"

[blocks.rawdata.args]
data_path = { ask = true }
scope_pixel = 2.1
scope_voltage = 300
scope_tilt_axis = 0.0

[blocks.preprocessing]
blockId = "tomo-preprocessing"
name = "Pre-processing"
parent = "rawdata"

[blocks.preprocessing.args]
movie_no_frames = true
ctf_max_res = 5.0
tomo_spk_method = "auto"
tomo_spk_rad = 80
tomo_spk_stdtimes_cont_3d = 2.0
tomo_spk_min_size_3d = 60
tomo_spk_dilation_3d = 100
tomo_spk_radiustimes_3d = 2.0
tomo_spk_inhibit_3d = true
tomo_spk_stdtimes_filt_3d = 2.0
tomo_spk_detection_width_3d = 40.0
tomo_rec_binning = 12
tomo_rec_thickness = 3072
tomo_rec_format = false
tomo_rec_erase_fiducials = true
slurm_tasks = { ask = true }            # e.g.: 42 for pre-processing, 124 for refinement
slurm_memory = { ask = true }           # e.g.: 420 for pre-processingm 720 for refinement
slurm_walltime = { ask = true }         # e.g.: 72:00:00
slurm_queue = { ask = true }
slurm_merge_tasks = { ask = true }      # e.g.: 13 for refinement, 100 for classification
slurm_merge_memory = { ask = true }     # e.g.: 20 for refinement, 200 for classification
slurm_merge_walltime = { ask = true }   # e.g.: 48:00:00
slurm_merge_queue = { ask = true }

[blocks.reference_refinement]
blockId = "tomo-coarse-refinement"
name = "Reference-based refinement"
parent = "preprocessing"

[blocks.reference_refinement.args]
refine_parfile_tomo = "auto"
particle_mw = 2000
particle_rad = 150
extract_box = 64
extract_bin = 4
refine_skip = true
refine_rhref = "22.0"
refine_fboost = true
reconstruct_mintilt = -50
reconstruct_maxtilt = 50
csp_ctf_handedness = true
csp_refine_particles = true
csp_UseImagesForRefinementMin = 15
csp_UseImagesForRefinementMax = 25
csp_NumberOfRandomIterations = 5000000
csp_ToleranceParticlesPhi = 180.0
csp_ToleranceParticlesTheta = 180.0
csp_ToleranceParticlesPsi = 180.0
csp_ToleranceParticlesShifts = 50.0
refine_model = { ask = true }

[blocks.particle_filtering]
blockId = "tomo-fine-refinement"
name = "Particle filtering"
parent = "reference_refinement"

[blocks.particle_filtering.args]
particle_mw = 2000
particle_rad = 150
extract_box = 64
extract_bin = 4
clean_threshold = 15.0
clean_dist = 20.0
clean_mintilt = -7.0
clean_maxtilt = 7.0
clean_min_num_projections = 1
clean_check_reconstruction = true
clean_parfile = 'auto'
refine_model = 'auto'

[blocks.particle_deep_clean]
blockId = "tomo-fine-refinement"
name = "Particle deep cleaning"
parent = "particle_filtering"

[blocks.particle_deep_clean.args]
clean_parfile = 'auto'
refine_model = 'auto'
clean_discard = true
particle_mw = 2000
particle_rad = 150
extract_box = 64
extract_bin = 4

[blocks.constrained_refinement]
blockId = "tomo-coarse-refinement"
name = "Fully constrained refinement"
parent = "particle_deep_clean"

[blocks.constrained_refinement.args]
refine_parfile = "auto"
refine_model = "auto"
particle_mw = 2000
particle_rad = 150
extract_box = 256
extract_bin = 1
refine_skip = true
refine_maxiter = 3
refine_rhref = "18:14"
refine_fboost = true
csp_refine_particles = true
csp_refine_micrographs = true
csp_OptimizerStepLength = 100.0
csp_UseImagesForRefinementMin = 15
csp_UseImagesForRefinementMax = 25
csp_NumberOfRandomIterations = 0
csp_ToleranceParticlesPsi = 30.0
csp_ToleranceParticlesPhi = 30.0
csp_ToleranceParticlesTheta = 30.0
csp_ToleranceParticlesShifts = 30.0
dose_weighting_enable = true
dose_weighting_fraction = 4
dose_weighting_global = true

[blocks.mask_generation]
blockId = "sp-masking"
name = "Create shape mask"
parent = "constrained_refinement"

[blocks.mask_generation.args]
mask_model = "auto"
mask_threshold = 0.4
mask_edge_width = 8

[blocks.region_refinement]
blockId = "tomo-coarse-refinement"
name = "Region-based refinement"
parent = "constrained_refinement"

[blocks.region_refinement.args]
refine_parfile = "auto"
refine_model = "auto"
refine_maskth = "auto"
particle_mw = 2000
particle_rad = 150
extract_box = 256
extract_bin = 1
refine_skip = true
refine_maxiter = 6
refine_rhref = "12:10:8:6:5"
refine_fboost = true
csp_refine_particles = true
csp_refine_micrographs = true
csp_OptimizerStepLength = 100.0
csp_UseImagesForRefinementMin = 18
csp_UseImagesForRefinementMax = 22
csp_NumberOfRandomIterations = 0
csp_ToleranceMicrographTiltAngles = 5.0
csp_ToleranceMicrographTiltAxisAngles = 5.0
csp_ToleranceParticlesPsi = 5.0
csp_ToleranceParticlesPhi = 5.0
csp_ToleranceParticlesTheta = 5.0
csp_ToleranceParticlesShifts = 20.0
csp_Grid = "8,8,2"
dose_weighting_enable = true
dose_weighting_fraction = 4
dose_weighting_global = true

[blocks.ctf_refinement]
blockId = "tomo-coarse-refinement"
name = "Particle-based CTF refinement"
parent = "region_refinement"

[blocks.ctf_refinement.args]
refine_parfile = "auto"
refine_model = "auto"
refine_maskth = "auto"
particle_mw = 2000
particle_rad = 150
extract_box = 256
extract_bin = 1
refine_skip = true
refine_maxiter = 2
refine_rhref = "4.5"
refine_fboost = true
csp_refine_particles = false
csp_refine_micrographs = false
csp_refine_ctf = true
csp_OptimizerStepLength = 100.0
csp_UseImagesForRefinementMin = 15
csp_UseImagesForRefinementMax = 25
csp_NumberOfRandomIterations = 0
csp_ToleranceMicrographDefocus1 = 2000
csp_ToleranceMicrographDefocus2 = 2000
csp_Grid = "8,8,2"
dose_weighting_enable = true
dose_weighting_fraction = 4
dose_weighting_global = true

[blocks.region_refinement_2]
blockId = "tomo-coarse-refinement"
name = "Region-based refinement 2"
parent = "ctf_refinement"

[blocks.region_refinement_2.args]
refine_parfile = "auto"
refine_model = "auto"
refine_maskth = "auto"
particle_mw = 2000
particle_rad = 150
extract_box = 256
extract_bin = 1
refine_skip = true
refine_maxiter = 4
refine_rhref = "6:5:4.5"
refine_fboost = true
csp_refine_particles = true
csp_refine_micrographs = true
csp_refine_ctf = false
csp_OptimizerStepLength = 20.0
csp_UseImagesForRefinementMin = 18
csp_UseImagesForRefinementMax = 22
csp_NumberOfRandomIterations = 0
csp_ToleranceMicrographShifts = 20.0
csp_ToleranceMicrographTiltAngles = 5.0
csp_ToleranceMicrographTiltAxisAngles = 5.0
csp_ToleranceParticlesPsi = 5.0
csp_ToleranceParticlesPhi = 5.0
csp_ToleranceParticlesTheta = 5.0
csp_ToleranceParticlesShifts = 20.0
csp_Grid = "16,16,4"
dose_weighting_enable = true
dose_weighting_fraction = 2
dose_weighting_global = true

[blocks.constrained_classification]
blockId = "tomo-coarse-refinement"
name = "Constrained classification"
parent = "region_refinement_2"

[blocks.constrained_classification.args]
refine_parfile = "auto"
refine_model = "auto"
refine_maskth = "auto"
particle_mw = 2000
particle_rad = 150
extract_box = 256
extract_bin = 1
refine_skip = false
refine_maxiter = 20
refine_rhref = "8"
refine_fboost = true
csp_refine_particles = false
csp_refine_micrographs = false
csp_refine_ctf = false
class_num = 8
class_rhcls = 8.0
dose_weighting_enable = true
dose_weighting_fraction = 2
dose_weighting_weights = "auto"
