
name = "Cellular lamellae (EMPIAR-11306)"
description = """\
    This workflow converts tilt-series from EMPIAR-11306 (ribosome) into a 5.0 A resolution structure.\
    """

# comments here are useful to share info with other workflow authors looking at this file
[blocks.rawdata]
blockId = "tomo-rawdata"
name = "Raw Data"

[blocks.rawdata.args]
data_path = "/nfs/bartesaghilab/nextpyp/lamellae/HeLa_argon/*.eer"
data_path_mdoc = "/nfs/bartesaghilab/nextpyp/lamellae/HeLa_argon/*.mdoc"
gain_reference = "/nfs/bartesaghilab/nextpyp/lamellae/HeLa_argon/gain_ref/20220406_175020_EER_GainReference.gain"
scope_pixel = 1.9
scope_voltage = 300
scope_tilt_axis = -174.23

[blocks.preprocessing]
blockId = "tomo-pure-preprocessing"
name = "Pre-processing"
parent = "rawdata"

[blocks.preprocessing.args]
movie_ali = "motioncor"
movie_pattern = "TILTSERIES_SCANORD_ANGLE_EER.eer"
movie_eer_frames = 10
ctf_max_res = 7.0
tomo_ali_method = "aretomo"
tomo_rec_method = "aretomo"
slurm_tasks = 11
slurm_memory = 44
slurm_walltime = "2:00:00"
slurm_merge_tasks = 6
slurm_merge_memory = 24
slurm_merge_walltime = "2:00:00"

[blocks.particlepicking]
blockId = "tomo-picking"
name = "Particle picking"
parent = "preprocessing"

[blocks.particlepicking.args]
tomo_pick_method = "auto"
tomo_pick_rad = 100
tomo_pick_radiustimes_3d = 1.0
tomo_pick_inhibit_3d = true
tomo_pick_detection_width_3d = 80
tomo_pick_stdtimes_filt_3d = 1.2
tomo_pick_remove_edge_3d = true
tomo_pick_rand = true
slurm_tasks = 4
slurm_memory = 22
slurm_walltime = "2:00:00"

[blocks.reference_refinement]
blockId = "tomo-coarse-refinement"
name = "Reference-based refinement"
parent = "particlepicking"

[blocks.reference_refinement.args]
refine_parfile_tomo = "auto"
particle_mw = 3000
particle_rad = 150
extract_box = 162
extract_bin = 2
extract_gold = false
refine_rhref = "20.0"
refine_fboost = true
refine_maskth = "/nfs/bartesaghilab/nextpyp/lamellae/mask_bin2.mrc"
refine_model = "/nfs/bartesaghilab/nextpyp/lamellae/emd_15636.mrc.mrc"
csp_UseImagesForRefinementMax = 16
csp_refine_particles = true
csp_ToleranceParticlesPhi = 180.0
csp_ToleranceParticlesTheta = 180.0
csp_ToleranceParticlesPsi = 90.0
csp_ToleranceParticlesShifts = 60.0
csp_NumberOfRandomIterations = 5000000
csp_ctf_handedness = true
slurm_tasks = 124
slurm_memory = 720
slurm_walltime = "72:00:00"

[blocks.particle_filtering]
blockId = "tomo-fine-refinement"
name = "Particle filtering"
parent = "reference_refinement"

[blocks.particle_filtering.args]
particle_mw = 3000
particle_rad = 150
extract_box = 162
extract_bin = 2
clean_threshold = 9.0
clean_dist = 100.0
clean_mintilt = -16.0
clean_maxtilt = 16.0
clean_check_reconstruction = true
clean_parfile = 'auto'
refine_model = 'auto'

[blocks.particle_deep_clean]
blockId = "tomo-fine-refinement"
name = "Particle deep cleaning"
parent = "particle_filtering"

[blocks.particle_deep_clean.args]
particle_mw = 3000
particle_rad = 150
extract_box = 162
extract_bin = 2
clean_parfile = 'auto'
refine_model = 'auto'
clean_discard = true

[blocks.constrained_refinement]
blockId = "tomo-coarse-refinement"
name = "Fully constrained refinement"
parent = "particle_deep_clean"

[blocks.constrained_refinement.args]
particle_mw = 3000
particle_rad = 150
extract_box = 162
extract_bin = 2
refine_parfile = "auto"
refine_model = "auto"
refine_skip = true
refine_maxiter = 6
refine_rhref = "10"
refine_fboost = false
refine_fssnr = false
refine_maskth = "/nfs/bartesaghilab/nextpyp/lamellae/mask_bin2.mrc"
reconstruct_mintilt = -50
reconstruct_maxtilt = 50
csp_refine_particles = true
csp_refine_micrographs = true
csp_UseImagesForRefinementMax = 12
csp_NumberOfRandomIterations = 0
csp_ToleranceParticlesPsi = 30.0
csp_ToleranceParticlesPhi = 30.0
csp_ToleranceParticlesTheta = 30.0
csp_ToleranceParticlesShifts = 30.0
dose_weighting_enable = true
dose_weighting_fraction = 4
dose_weighting_global = true
csp_ctf_handedness = true
slurm_tasks = 124
slurm_memory = 720
slurm_walltime = "72:00:00"

[blocks.dose_weighting]
blockId = "tomo-coarse-refinement"
name = "Dose weighting"
parent = "constrained_refinement"

[blocks.dose_weighting.args]
particle_mw = 3000
particle_rad = 150
extract_box = 162
extract_bin = 2
refine_parfile = "auto"
refine_model = "auto"
refine_maxiter = 3
refine_rhref = "8"
refine_maskth = "/nfs/bartesaghilab/nextpyp/lamellae/mask_bin2.mrc"
dose_weighting_enable = true
dose_weighting_fraction = 6
dose_weighting_global = true

[blocks.region_refinement]
blockId = "tomo-coarse-refinement"
name = "Region-based refinement"
parent = "dose_weighting"

[blocks.region_refinement.args]
particle_mw = 3000
particle_rad = 150
extract_box = 162
extract_bin = 2
refine_parfile = "auto"
refine_model = "auto"
refine_rhref = "6"
refine_maskth = "/nfs/bartesaghilab/nextpyp/lamellae/mask_bin2.mrc"
csp_Grid = "4,4,4"

[blocks.unbinned_refinement]
blockId = "tomo-coarse-refinement"
name = "Unbnned refinement"
parent = "region_refinement"

[blocks.unbinned_refinement.args]
particle_mw = 3000
particle_rad = 150
extract_box = 324
extract_bin = 1
refine_parfile = "auto"
refine_model = "auto"
refine_maxiter = 3
refine_rhref = "6:5"
refine_maskth = "/nfs/bartesaghilab/nextpyp/lamellae/mask_bin1.mrc"
csp_ToleranceParticlesShifts = 30.0
dose_weighting_fraction = 7

[blocks.ctf_refinement]
blockId = "tomo-coarse-refinement"
name = "Particle-based CTF refinement"
parent = "unbinned_refinement"

[blocks.ctf_refinement.args]
particle_mw = 3000
particle_rad = 150
extract_box = 324
extract_bin = 1
refine_parfile = "auto"
refine_model = "auto"
refine_maxiter = 2
refine_maskth = "/nfs/bartesaghilab/nextpyp/lamellae/mask_bin1.mrc"
csp_refine_particles = false
csp_refine_micrographs = false
csp_refine_ctf = true
csp_ToleranceMicrographDefocus1 = 2000
csp_ToleranceMicrographDefocus2 = 2000
denoise_enable = true

[blocks.region_refinement_2]
blockId = "tomo-coarse-refinement"
name = "Region-based refinement 2"
parent = "ctf_refinement"

[blocks.region_refinement_2.args]
particle_mw = 3000
particle_rad = 150
extract_box = 324
extract_bin = 1
refine_parfile = "auto"
refine_model = "auto"
refine_maskth = "/nfs/bartesaghilab/nextpyp/lamellae/mask_bin1.mrc"
refine_maxiter = 4
refine_rhref = "5:5:4.8:4.5"
csp_refine_particles = true
csp_refine_micrographs = true
csp_refine_ctf = false

[blocks.sharpening]
blockId = "sp-postprocessing"
name = "Map-sharpening"
parent = "region_refinement_2"

[blocks.sharpening.args]
sharpen_input_map = 'auto'
sharpen_automask_threshold = 0.35
sharpen_adhoc_bfac = -25
