
name = "Tomography tutorial (EMPIAR-10164)"
description = """\
    This tutorial shows the end-to-end process to convert raw movies from EMPIAR-10164 (HIV-1 Gag) into a ~3A resolution structure.\
    """

# comments here are useful to share info with other workflow authors looking at this file
[blocks.rawdata]
blockId = "tomo-rawdata"
name = "Raw Data"

[blocks.rawdata.args]
data_path = { ask = true }
scope_pixel = 1.35
scope_voltage = 300
scope_tilt_axis = 85.3

[blocks.preprocessing]
blockId = "tomo-pure-preprocessing"
name = "Pre-processing"
parent = "rawdata"

[blocks.preprocessing.args]
movie_pattern = "TILTSERIES_SCANORD_ANGLE.tif"
ctf_max_res = 5.0
tomo_rec_binning = 8
tomo_rec_thickness = 2048
slurm_tasks = { ask = true }            # e.g.: 42 (124 for refinement)
slurm_memory = { ask = true }           # e.g.: 420 (720 for refinement)
slurm_walltime = { ask = true }         # e.g.: 20:00:00
slurm_queue = { ask = true }
slurm_merge_tasks = { ask = true }      # e.g.: 6
slurm_merge_memory = { ask = true }     # e.g.: 20
slurm_merge_walltime = { ask = true }   # e.g.: 20:00:00
slurm_merge_queue = { ask = true }

[blocks.particlepicking]
blockId = "tomo-picking"
name = "Particle picking"
parent = "preprocessing"

[blocks.particlepicking.args]
tomo_pick_method = "virions"
tomo_pick_vir_rad = 500

[blocks.segmentation]
blockId = "tomo-segmentation-closed"
name = "Segmentation"
parent = "particlepicking"

[blocks.segmentation.args]

[blocks.particlepickingclosed]
blockId = "tomo-picking-closed"
name = "Constrained particle picking"
parent = "segmentation"

[blocks.particlepickingclosed.args]
tomo_srf_detect_method = "mesh"
tomo_srf_detect_band = 800
tomo_srf_detect_rad = 50
tomo_srf_detect_dist = 8

[blocks.reference_refinement]
blockId = "tomo-coarse-refinement"
name = "Reference-based refinement"
parent = "particlepickingclosed"

[blocks.reference_refinement.args]
refine_parfile_tomo = "auto"
particle_mw = 300
particle_rad = 150
particle_sym = "C6"
extract_box = 192
extract_gold = false
extract_bin = 2
refine_rhref = "8.0"
refine_fboost = true
reconstruct_mintilt = -50
reconstruct_maxtilt = 50
csp_refine_particles = true
csp_UseImagesForRefinementMax = 10
csp_NumberOfRandomIterations = 50000
csp_ToleranceParticlesPhi = 10.0
csp_ToleranceParticlesTheta = 10.0
csp_ToleranceParticlesShifts = 50.0

[blocks.constrained_refinement]
blockId = "tomo-coarse-refinement"
name = "Fully constrained refinement"
parent = "reference_refinement"

[blocks.constrained_refinement.args]
refine_parfile = "auto"
refine_model = "auto"
particle_mw = 300
particle_rad = 150
particle_sym = "C6"
extract_box = 192
extract_bin = 2
refine_maxiter = 4
refine_rhref = "10:8:6"
refine_fboost = true
csp_refine_particles = true
csp_refine_micrographs = true
csp_OptimizerStepLength = 100.0
csp_UseImagesForRefinementMax = 10
csp_NumberOfRandomIterations = 0
csp_ToleranceParticlesPsi = 20.0
csp_ToleranceParticlesPhi = 20.0
csp_ToleranceParticlesTheta = 20.0
csp_ToleranceParticlesShifts = 100.0
dose_weighting_enable = true
dose_weighting_fraction = 4

[blocks.particle_filtering]
blockId = "tomo-fine-refinement"
name = "Particle filtering"
parent = "constrained_refinement"

[blocks.particle_filtering.args]
clean_threshold = 2.5
clean_dist = 10.0
clean_mintilt = -15.0
clean_maxtilt = 15.0
clean_min_num_projections = 1
clean_check_reconstruction = true
clean_parfile = 'auto'
refine_model = 'auto'

[blocks.particle_deep_clean]
blockId = "tomo-fine-refinement"
name = "Particle deep cleaning"
parent = "particle_filtering"

[blocks.particle_deep_clean.args]
clean_parfile = 'auto'
refine_model = 'auto'
clean_discard = true

[blocks.region_refinement]
blockId = "tomo-coarse-refinement"
name = "Region-based refinement"
parent = "particle_deep_clean"

[blocks.region_refinement.args]
refine_parfile = "auto"
refine_model = "auto"
particle_mw = 300
particle_rad = 100
particle_sym = "C6"
extract_box = 384
extract_bin = 1
refine_maxiter = 3
refine_rhref = "6:5"
refine_fboost = true
csp_refine_particles = true
csp_refine_micrographs = true
csp_OptimizerStepLength = 100.0
csp_UseImagesForRefinementMax = 4
csp_NumberOfRandomIterations = 0
csp_ToleranceParticlesPsi = 20.0
csp_ToleranceParticlesPhi = 20.0
csp_ToleranceParticlesTheta = 20.0
csp_ToleranceParticlesShifts = 20.0
csp_Grid = "8,8,2"
dose_weighting_enable = true
dose_weighting_fraction = 4

[blocks.mask_generation]
blockId = "sp-masking"
name = "Create shape mask"
parent = "region_refinement"

[blocks.mask_generation.args]
mask_model = "auto"
mask_threshold = 0.42
mask_edge_width = 8

[blocks.region_refinement_2]
blockId = "tomo-coarse-refinement"
name = "Region-based refinement 2"
parent = "region_refinement"

[blocks.region_refinement_2.args]
refine_parfile = "auto"
refine_model = "auto"
refine_maskth = { ask = true }
particle_mw = 300
particle_rad = 100
particle_sym = "C6"
extract_box = 384
extract_bin = 1
refine_maxiter = 4
refine_rhref = "5:4:3.5"
refine_fboost = true
csp_refine_particles = true
csp_refine_micrographs = true
csp_OptimizerStepLength = 100.0
csp_UseImagesForRefinementMax = 4
csp_NumberOfRandomIterations = 0
csp_ToleranceParticlesPsi = 20.0
csp_ToleranceParticlesPhi = 20.0
csp_ToleranceParticlesTheta = 20.0
csp_ToleranceParticlesShifts = 20.0
csp_Grid = "8,8,2"
dose_weighting_enable = true
dose_weighting_fraction = 4

[blocks.ctf_refinement]
blockId = "tomo-coarse-refinement"
name = "Particle-based CTF refinement"
parent = "region_refinement_2"

[blocks.ctf_refinement.args]
refine_parfile = "auto"
refine_model = "auto"
particle_mw = 300
particle_rad = 100
particle_sym = "C6"
extract_box = 384
extract_bin = 1
refine_maxiter = 2
refine_rhref = "3.1"
refine_fboost = true
csp_refine_particles = false
csp_refine_micrographs = false
csp_refine_ctf = true
csp_OptimizerStepLength = 100.0
csp_UseImagesForRefinementMax = 10
csp_NumberOfRandomIterations = 0
csp_Grid = "8,8,2"
dose_weighting_enable = true
dose_weighting_fraction = 4

[blocks.movie_refinement]
blockId = "tomo-flexible-refinement"
name = "Movie refinement"
parent = "ctf_refinement"

[blocks.movie_refinement.args]
refine_parfile = "auto"
refine_model = "auto"
particle_mw = 300
particle_rad = 80
particle_sym = "C6"
extract_box = 384
extract_bin = 1
refine_maxiter = 2
refine_rhref = "3.2"
refine_fboost = true
csp_transreg = true
csp_spatial_sigma = 200.0
dose_weighting_enable = true
dose_weighting_fraction = 4
csp_frame_refinement = true
csp_refine_ctf = false
csp_UseImagesForRefinementMax = 4

[blocks.refinement_after_movie_refinement]
blockId = "tomo-flexible-refinement"
name = "Refinement after movie refinement"
parent = "movie_refinement"

[blocks.refinement_after_movie_refinement.args]
refine_parfile = "auto"
refine_model = "auto"
particle_mw = 300
particle_rad = 80
particle_sym = "C6"
extract_box = 384
extract_bin = 1
refine_maxiter = 2
refine_rhref = "3.3"
refine_fboost = true
csp_frame_refinement = false
csp_refine_particles = true
csp_refine_micrographs = true
csp_OptimizerStepLength = 100.0
csp_UseImagesForRefinementMax = 4
csp_NumberOfRandomIterations = 0
csp_ToleranceParticlesPsi = 1.0
csp_ToleranceParticlesPhi = 1.0
csp_ToleranceParticlesTheta = 1.0
csp_ToleranceParticlesShifts = 10.0
csp_RefineProjectionCutoff = 2
csp_ToleranceMicrographShifts = 10.0
csp_ToleranceMicrographTiltAngles = 1.0
csp_ToleranceMicrographTiltAxisAngles = 1.0

csp_Grid = "8,8,2"
dose_weighting_enable = true
dose_weighting_fraction = 4

[blocks.sharpening]
blockId = "sp-postprocessing"
name = "Map-sharpening"
parent = "refinement_after_movie_refinement"

[blocks.sharpening.args]
sharpen_input_map = 'auto'
sharpen_automask_threshold = 0.35
sharpen_adhoc_bfac = -25
