
name = "Tomography tutorial (EMPIAR-10164)"
description = """\
    This tutorial shows the end-to-end process to convert raw movies from EMPIAR-10164 (HIV-1 Gag) into a ~3A resolution structure.\
    """

# comments here are useful to share info with other workflow authors looking at this file
[blocks.rawdata]
blockId = "tomo-rawdata"
name = "Raw Data"

[blocks.rawdata.args]
data_path = { ask = true }
scope_pixel = 1.35
scope_voltage = 300
scope_tilt_axis = 85.3

[blocks.preprocessing]
blockId = "tomo-pure-preprocessing"
name = "Pre-processing"
parent = "rawdata"

[blocks.preprocessing.args]
movie_pattern = "TILTSERIES_SCANORD_ANGLE.tif"
ctf_max_res = 5.0
tomo_rec_binning = 8
tomo_rec_thickness = 2048
slurm_tasks = { ask = true }            # e.g.: 42 (124 for refinement)
slurm_merge_tasks = { ask = true }      # e.g.: 6

[blocks.particlepicking]
blockId = "tomo-picking"
name = "Particle picking"
parent = "preprocessing"

[blocks.particlepicking.args]
tomo_pick_method = "virions"
tomo_pick_vir_rad = 500

[blocks.segmentation]
blockId = "tomo-segmentation-closed"
name = "Segmentation"
parent = "particlepicking"

[blocks.segmentation.args]

[blocks.particlepickingclosed]
blockId = "tomo-picking-closed"
name = "Constrained particle picking"
parent = "segmentation"

[blocks.particlepickingclosed.args]
tomo_srf_detect_method = "mesh"
tomo_srf_detect_band = 800
tomo_srf_detect_rad = 50
tomo_srf_detect_dist = 8

[blocks.reference_refinement]
blockId = "tomo-reference-refinement"
name = "Reference-based refinement"
parent = "particlepickingclosed"

[blocks.reference_refinement.args]
particle_mw = 300
particle_rad = 150
particle_sym = "C6"
extract_box = 192
extract_gold = false
extract_bin = 2
metric_rhref = "8.0"
metric_fboost = true
metric_UseImagesForRefinementMax = 10
reconstruct_mintilt = -50
reconstruct_maxtilt = 50
csp_tomo_reference_AngleStep = 2
csp_tomo_reference_ToleranceParticlesPsi = 10.0
csp_tomo_reference_ToleranceParticlesTheta = 10.0
csp_tomo_reference_ToleranceParticlesShifts = 50.0
csp_tomo_reference_ShiftStep = 6

[blocks.constrained_refinement]
blockId = "tomo-new-coarse-refinement"
name = "Fully constrained refinement"
parent = "reference_refinement"

[blocks.constrained_refinement.args]
particle_mw = 300
particle_rad = 150
particle_sym = "C6"
extract_box = 192
extract_bin = 2
metric_fboost = true
metric_UseImagesForRefinementMax = 10
metric_rhref = "10:8:6"
csp_tomo_coarse_parfile = "auto"
csp_tomo_coarse_maxiter = 4
csp_tomo_coarse_refine_particles = true
csp_tomo_coarse_refine_micrographs = true
csp_tomo_coarse_OptimizerStepLength = 100.0
csp_tomo_coarse_NumberOfRandomIterations = 0
csp_tomo_coarse_ToleranceParticlesPsi = 20.0
csp_tomo_coarse_ToleranceParticlesPhi = 20.0
csp_tomo_coarse_ToleranceParticlesTheta = 20.0
csp_tomo_coarse_ToleranceParticlesShifts = 100.0
reconstruct_dose_weighting_enable = true
reconstruct_dose_weighting_fraction = 4

[blocks.particle_filtering]
blockId = "tomo-fine-refinement"
name = "Particle filtering"
parent = "constrained_refinement"

[blocks.particle_filtering.args]
clean_threshold = 2.5
clean_dist = 10.0
clean_mintilt = -15.0
clean_maxtilt = 15.0
clean_min_num_projections = 1
clean_check_reconstruction = true
clean_discard = true
clean_parfile = 'auto'

[blocks.region_refinement]
blockId = "tomo-new-coarse-refinement"
name = "Region-based refinement"
parent = "particle_filtering"

[blocks.region_refinement.args]
particle_mw = 300
particle_rad = 100
particle_sym = "C6"
extract_box = 384
extract_bin = 1
metric_fboost = true
metric_UseImagesForRefinementMax = 4
metric_rhref = "6:5"
csp_tomo_coarse_parfile = "auto"
csp_tomo_coarse_maxiter = 3
csp_tomo_coarse_refine_particles = true
csp_tomo_coarse_refine_micrographs = true
csp_tomo_coarse_OptimizerStepLength = 100.0
csp_tomo_coarse_NumberOfRandomIterations = 0
csp_tomo_coarse_ToleranceParticlesPsi = 20.0
csp_tomo_coarse_ToleranceParticlesPhi = 20.0
csp_tomo_coarse_ToleranceParticlesTheta = 20.0
csp_tomo_coarse_ToleranceParticlesShifts = 20.0
csp_tomo_coarse_Grid = "8,8,2"
reconstruct_dose_weighting_enable = true
reconstruct_dose_weighting_fraction = 4

[blocks.mask_generation]
blockId = "sp-masking"
name = "Create shape mask"
parent = "region_refinement"

[blocks.mask_generation.args]
mask_model = "auto"
mask_threshold = 0.45
mask_edge_width = 8

[blocks.region_refinement_2]
blockId = "tomo-new-coarse-refinement"
name = "Region-based refinement 2"
parent = "region_refinement"

[blocks.region_refinement_2.args]
particle_mw = 300
particle_rad = 100
particle_sym = "C6"
extract_box = 384
extract_bin = 1
metric_fboost = true
metric_UseImagesForRefinementMax = 4
metric_masking_method = "file"
metric_maskth = { ask = true }
metric_rhref = "5:4:3.5"
csp_tomo_coarse_parfile = "auto"
csp_tomo_coarse_maxiter = 4
csp_tomo_coarse_refine_particles = true
csp_tomo_coarse_refine_micrographs = true
csp_tomo_coarse_OptimizerStepLength = 100.0
csp_tomo_coarse_NumberOfRandomIterations = 0
csp_tomo_coarse_ToleranceParticlesPsi = 20.0
csp_tomo_coarse_ToleranceParticlesPhi = 20.0
csp_tomo_coarse_ToleranceParticlesTheta = 20.0
csp_tomo_coarse_ToleranceParticlesShifts = 20.0
csp_tomo_coarse_Grid = "8,8,2"
reconstruct_dose_weighting_enable = true
reconstruct_dose_weighting_fraction = 4

[blocks.ctf_refinement]
blockId = "tomo-new-coarse-refinement"
name = "Particle-based CTF refinement"
parent = "region_refinement_2"

[blocks.ctf_refinement.args]
particle_mw = 300
particle_rad = 80
particle_sym = "C6"
extract_box = 384
extract_bin = 1
metric_fboost = true
metric_UseImagesForRefinementMax = 10
metric_rhref = "3.1"
csp_tomo_coarse_parfile = "auto"
csp_tomo_coarse_maxiter = 2
csp_tomo_coarse_refine_particles = false
csp_tomo_coarse_refine_micrographs = false
csp_tomo_coarse_refine_ctf = true
csp_tomo_coarse_OptimizerStepLength = 100.0
csp_tomo_coarse_NumberOfRandomIterations = 0
csp_tomo_coarse_Grid = "8,8,2"
reconstruct_dose_weighting_enable = true
reconstruct_dose_weighting_fraction = 4

[blocks.movie_refinement]
blockId = "tomo-flexible-refinement"
name = "Movie refinement"
parent = "ctf_refinement"

[blocks.movie_refinement.args]
particle_mw = 300
particle_rad = 80
particle_sym = "C6"
extract_box = 384
extract_bin = 1
metric_fboost = true
metric_UseImagesForRefinementMax = 4
metric_rhref = "3.2"
csp_tomo_movie_parfile = "auto"
csp_tomo_movie_maxiter = 2
csp_tomo_movie_transreg = true
csp_tomo_movie_spatial_sigma = 200.0
reconstruct_dose_weighting_enable = true
reconstruct_dose_weighting_fraction = 4

[blocks.refinement_after_movie_refinement]
blockId = "tomo-flexible-refinement-after"
name = "Refinement after movie refinement"
parent = "movie_refinement"

[blocks.refinement_after_movie_refinement.args]
particle_mw = 300
particle_rad = 80
particle_sym = "C6"
extract_box = 384
extract_bin = 1
metric_fboost = true
metric_rhref = "3.3"
metric_UseImagesForRefinementMax = 4
metric_RefineProjectionCutoff = 2
csp_tomo_movie_after_parfile = "auto"
csp_tomo_movie_after_maxiter = 2
csp_tomo_movie_after_refine_particles = true
csp_tomo_movie_after_refine_micrographs = true
csp_tomo_movie_after_OptimizerStepLength = 100.0
csp_tomo_movie_after_NumberOfRandomIterations = 0
csp_tomo_movie_after_ToleranceParticlesPsi = 1.0
csp_tomo_movie_after_ToleranceParticlesPhi = 1.0
csp_tomo_movie_after_ToleranceParticlesTheta = 1.0
csp_tomo_movie_after_ToleranceParticlesShifts = 10.0
csp_tomo_movie_after_ToleranceMicrographShifts = 10.0
csp_tomo_movie_after_ToleranceMicrographTiltAngles = 1.0
csp_tomo_movie_after_ToleranceMicrographTiltAxisAngles = 1.0
reconstruct_dose_weighting_enable = true
reconstruct_dose_weighting_fraction = 4

[blocks.sharpening]
blockId = "sp-postprocessing"
name = "Map-sharpening"
parent = "refinement_after_movie_refinement"

[blocks.sharpening.args]
sharpen_input_map = 'auto'
sharpen_automask_threshold = 0.35
sharpen_bfactor_method = 'adhoc'
sharpen_adhoc_bfac = -25
slurm_tasks = 11