#!/bin/sh

# exit if any command fails
set -e


if [ "$(whoami)" != "root" ]; then
  echo "This utility should be run as root!"
  exit 1
fi


# process the command
case "$1" in

  add)

    # get the username
    username=$2
    if [ -z "$username" ]; then
      echo "Required argument: username"
      exit 1
    fi
    if [ "$username" = "root" ]; then
      echo "Root is not an allowed user"
      exit 1
    fi

    # make a way to run commands as the target user
    usdo="sudo -u $username"

    # create the user-processor executable for this user
    exec="user-processor-$username"
    $usdo cp user-processor "$exec"

    # only the user should be able to write
    # only the user and the group should be able to execute
    chmod u=rwx,g=rx,o= "$exec"

    # the executable should be setuid
    # NOTE: set this last, so we're sure the executable has the correct permissions before turning on setuid
    chmod u+s "$exec"

    ;;


  remove)

    # get the username
    username=$2
    if [ -z "$username" ]; then
      echo "Required argument: username"
      exit 1
    fi
    if [ "$username" = "root" ]; then
      echo "Root is not an allowed user"
      exit 1
    fi

    # make a way to run commands as the target user
    usdo="sudo -u $username"

    # remove the runas-username executable, if any
    exec=user-processor-$username
    if [ -f "$exec" ]; then
      $usdo rm "$exec"
    else
      echo "No user-processor executable found for user $username"
      exit 1
    fi

    ;;


  *)
    echo "Usage:"
    echo "   ./admin-user-processor <add | remove> <username>"
    echo "Run this script inside of the <nextpyp-local>/user-processor/exec folder"
    exit 1
    ;;


esac