#!/bin/sh


# the uninstaller should be run as root
if [ "$(whoami)" != "root" ]; then
  echo "This uninstaller should be run as root"
  exit 1
fi


echo "Uninstalling nextPYP reverse proxy HTTP server ..."


# uninstall systemd integrations
rproxDaemon="nextPYP-rprox"
systemctl disable $rproxDaemon 2> /dev/null
systemctl stop $rproxDaemon 2> /dev/null
rm "/lib/systemd/system/$rproxDaemon.service" 2> /dev/null

# poke systemd to recognize the removal of the daemon
systemctl daemon-reload


# delete the executables from /usr/bin
rm "/usr/bin/nextpyp-startrprox" 2> /dev/null
rm "/usr/bin/nextpyp-stoprprox" 2> /dev/null


# assume the installation folder is the same one this script is in
here=$(dirname "$0")

# delete the files the installer downloaded
rm "$here/reverse-proxy.sif" 2> /dev/null
rm "$here/uninstall-rprox" 2> /dev/null


echo "Finished uninstalling nextPYP reverse proxy HTTP server."
